version: '3'
services:
  webapp:
    build: ./images/webapp
    ports:
      - "$WEBAPP_PORT:80"
    depends_on:
      - db
      - elasticsearch
    environment:
      - ROOT_URL=$ROOT_URL
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - ELASTICSEARCH_URL=$ELASTICSEARCH_URL
      - DB_NAME=$DB_NAME
      - GITHUB_TOKEN=$GITHUB_TOKEN
  db:
    build: ./images/db
    ports:
      - "27017:27017"
    environment:
      -  MONGO_HOST=$MONGO_HOST
      -  OPLOG_USER=$OPLOG_USER
      -  OPLOG_PASSWORD=$OPLOG_PASSWORD
  elasticsearch:
    image: "elasticsearch:5"
    ports:
      - "9200:9200"
  mongoconnector:
    build: ./images/mongo-connector
    depends_on:
      - db
      - elasticsearch
    environment:
      - MONGO_URL=$MONGO_URL
      - ELASTICSEARCH_URL=$ELASTICSEARCH_URL
  scheduler:
    build: ./images/calculation-scheduler
    depends_on:
      - db
      - tensormol-service
      - psi4-service
      - pyscf-service
    environment:
      - ROOT_URL=http://scheduler:4000/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - TENSORMOL_URL=$TENSORMOL_URL
      - PSI4_URL=$PSI4_URL
      - PYSCF_URL=$PYSCF_URL
      - GITHUB_TOKEN=$GITHUB_TOKEN
  tensormol-service:
    build: ./images/tensormol-service
    depends_on:
      - db
    environment:
      - ROOT_URL=http://tensormol-service:4100/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - GITHUB_TOKEN=$GITHUB_TOKEN
  psi4-service:
    build: ./images/psi4-service
    depends_on:
      - db
    environment:
      - ROOT_URL=http://psi4-service:4200/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - OMP_NUM_THREADS=$PSI4_NUM_THREADS
      - PSI4_MAX_MEMORY=$PSI4_MAX_MEMORY
      - GITHUB_TOKEN=$GITHUB_TOKEN
  pyscf-service:
    build: ./images/pyscf-service
    depends_on:
      - db
    environment:
      - ROOT_URL=http://pyscf-service:4300/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - OMP_NUM_THREADS=$PYSCF_NUM_THREADS
      - PYSCF_MAX_MEMORY=$PYSCF_MAX_MEMORY
      - GITHUB_TOKEN=$GITHUB_TOKEN