version: '3'
services:
  about:
    build: ./images/about
    ports:
      - "$ABOUT_PORT:80"
    environment:
      - ROOT_URL=$ABOUT_ROOT_URL
  webapp:
    build: ./images/webapp
    ports:
      - "$WEBAPP_PORT:80"
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - ROOT_URL=$WEBAPP_ROOT_URL
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - ELASTICSEARCH_URL=$ELASTICSEARCH_URL
      - DB_NAME=$DB_NAME
      - GITHUB_TOKEN=$GITHUB_TOKEN
  mongo:
    build: ./images/mongo
    ports:
      - "$MONGO_PORT:27017"
    environment:
      -  MONGO_HOST=$MONGO_HOST
      -  OPLOG_USER=$OPLOG_USER
      -  OPLOG_PASSWORD=$OPLOG_PASSWORD
  elasticsearch:
    image: "elasticsearch:5"
    ports:
      - "9200:9200"
  mongoconnector:
    build: ./images/mongo-connector
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - MONGO_URL=$MONGO_URL
      - ELASTICSEARCH_URL=$ELASTICSEARCH_URL
  image-generator:
    build: ./images/image-generator
    environment:
      - ROOT_URL=http://image-generator:4000/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
  database:
    build: ./images/database
    depends_on:
      - mongo
    environment:
      - ROOT_URL=http://database:4000/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - TENSORMOL_URL=$TENSORMOL_URL
      - PSI4_URL=$PSI4_URL
      - PYSCF_URL=$PYSCF_URL
      - GITHUB_TOKEN=$GITHUB_TOKEN
  tensormol:
    build: ./images/tensormol
    depends_on:
      - database
    environment:
      - ROOT_URL=http://tensormol:4100/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - GITHUB_TOKEN=$GITHUB_TOKEN
  psi4:
    build: ./images/psi4
    depends_on:
      - database
    environment:
      - ROOT_URL=http://psi4:4200/
      - MONGO_URL=$METEOR_MONGO_URL
      - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
      - OMP_NUM_THREADS=$PSI4_NUM_THREADS
      - PSI4_MAX_MEMORY=$PSI4_MAX_MEMORY
      - GITHUB_TOKEN=$GITHUB_TOKEN
  # pyscf:
  #   build: ./images/pyscf
  #   depends_on:
  #     - mongo
  #   environment:
  #     - ROOT_URL=http://pyscf:4300/
  #     - MONGO_URL=$METEOR_MONGO_URL
  #     - MONGO_OPLOG_URL=$MONGO_OPLOG_URL
  #     - OMP_NUM_THREADS=$PYSCF_NUM_THREADS
  #     - PYSCF_MAX_MEMORY=$PYSCF_MAX_MEMORY
  #     - GITHUB_TOKEN=$GITHUB_TOKEN
